version: '3.8'

services:
  web:
    build: .
    command: supervisord -c /etc/supervisor/conf.d/supervisord.conf
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

