# Generated by Django 5.0.6 on 2024-06-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_click_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickedproduct',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
