# Generated by Django 5.0.6 on 2024-06-25 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_clickedproduct_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='click_count',
        ),
    ]
