# Generated by Django 5.0.6 on 2024-06-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_vendorrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorrequest',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorrequest',
            name='zip_code',
            field=models.CharField(max_length=20),
        ),
    ]
