# Generated by Django 5.0.6 on 2024-06-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_vendorrequest_status_alter_vendorrequest_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorrequest',
            name='activity',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=20),
        ),
    ]
