# Generated by Django 5.0.6 on 2024-06-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_product_image_product_image_base64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_base64',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
