# Generated by Django 5.0.6 on 2024-06-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_helpcategory_helparticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPoliciesGuidelines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Vendor Policies and Guidelines', max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
